gText_Birch_Welcome:: @ 82C897B
	.string "Hello! Welcome to POKéMON SWOWS. My\n"
	.string "name is ALEXANDER. I made this hack.\p"
	.string "If the tin didn't clue you in, this is a\n"
	.string "ROM hack of POKéMON EMERALD!\p"
	.string "This hack is made possible by PRET,\n"
	.string "and their “pokeemerald” disassembly.\l"
	.string "Send them your shiniest postcards.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This is what we call a “LOTAD.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "This hack takes place in the familiar\n"
	.string "region of HOENN, with 386 POKéMON too.\p"
	.string "But it's been updated considerably!\p"
	.string "Dialogues have been redone, the story\n"
	.string "has been deepened a bit, and more.\l"
	.string "It should be a bit funnier too.\p"
	.string "I wanted to make this hack for years,\n"
	.string "and now I think the timing is right.\p"
	.string "In the years before the disassemblies,\n"
	.string "I innovated a hybrid hacking method,\l"
	.string "called “source-based hacking”.\p"
	.string "That proved too laborious for me, so I\n"
	.string "quit and moved on to other things.\p"
	.string "I don't know how much gameplay will be\n"
	.string "changed in this hack.\p"
	.string "I'd love to hear suggestions though.\n"
	.string "See the README file to get in touch.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "Anyways, you are…?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "Alright.\n"
	.string "You got a name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving into\n"
	.string "LITTLEROOT TOWN.\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "That's all the info I'll need for now.\p"
	.string "I hope you've played POKéMON before,\n"
	.string "because you won't find extra help here!\p"
	.string "Just a reminder: BIRCH will want to see\n"
	.string "you at some point.\l"
	.string "He wanted you to know as I cut him out.\p"
	.string "Good luck, {PLAYER}{KUN}!\p"
	.string "$"
